ds

diff --git a/app/Dockerfile b/app/Dockerfile
--- a/app/Dockerfile
+++ b/app/Dockerfile
@@ -1,17 +1,3 @@
-# Copyright (c) 2024 Contributors to the Eclipse Foundation
-#
-# This program and the accompanying materials are made available under the
-# terms of the Apache License, Version 2.0 which is available at
-# https://www.apache.org/licenses/LICENSE-2.0.
-#
-# Unless required by applicable law or agreed to in writing, software
-# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
-# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
-# License for the specific language governing permissions and limitations
-# under the License.
-#
-# SPDX-License-Identifier: Apache-2.0
-
 # syntax=docker/dockerfile:1.2
 
 # Build stage, to create the executable
@@ -32,9 +18,6 @@ RUN pip3 install --no-cache-dir grpcio==1.64.1 grpcio-tools==1.64.1
 WORKDIR /workspace
 COPY ./.velocitas.json /workspace/.velocitas.json
 COPY ./app /workspace/app
-
-# Check if the directory ./app/src/vehicle_model/proto exists
-RUN ls -l ./app/src/vehicle_model/proto
 
 # Copy proto files into the workspace
 COPY ./app/src/vehicle_model/proto /workspace/proto
@@ -65,7 +48,7 @@ RUN pip3 install --no-cache-dir patchelf==0.17.0.0 && patchelf --version
 
 # Debugging step for staticx installation
 RUN pip3 install --no-cache-dir staticx
-RUN staticx --version || echo "Staticx installation failed" && exit 1
+RUN staticx --version || (echo "Staticx installation failed" && exit 1)
 
 RUN pip3 install --no-cache-dir scons && scons --version
 
@@ -77,7 +60,7 @@ RUN pyinstaller --clean -F -s --paths=src src/main.py
 WORKDIR /workspace/app/dist
 
 # Use staticx to create a statically linked executable
-RUN staticx main run-exe
+RUN staticx main run-exe || (echo "Staticx execution failed" && exit 1)
 
 # Runner stage, to copy the executable
 FROM scratch as runner
